backend = "glx";

shadow = false;
fading = true;

# Exclude xsecurelock from fades. It must map instantly at full opacity, or
# else it reports the compositor as incompatible
fade-exclude = [ "class_g ?= 'xsecurelock'" ];

# Time between fade steps, in milliseconds
fade-delta = 2;
fade-in-step = 0.05;
fade-out-step = 0.05;

wintypes:
{
    menu = { fade = false; };
    popup_menu = { fade = false; };
    dropdown_menu = { fade = false; };
    tooltip = { fade = false; };
};
