[colors.cursor]
cursor = "{{black_almost}}"
text = "{{white}}"

[colors.normal]
black = "{{black_almost}}"
red = "{{red}}"
green = "{{green}}"
yellow = "{{yellow}}"
blue = "{{blue}}"
magenta = "{{magenta}}"
cyan = "{{lavender}}"
white = "{{gray_dark}}"

[colors.bright]
black = "{{black_almost}}"
red = "{{red}}"
green = "{{green}}"
yellow = "{{yellow}}"
blue = "{{blue}}"
magenta = "{{magenta}}"
cyan = "{{lavender}}"
white = "{{gray_dark}}"

[colors.primary]
background = "{{white}}"
foreground = "{{black}}"

[colors.hints.start]
foreground = "{{black}}"
background = "{{green_bright}}"

[colors.hints.end]
foreground = "{{black}}"
background = "{{green_bright}}"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = {{term_font_size}}

[font.normal]
family = "{{term_font_family}}"
style = "Medium"

[font.bold]
family = "{{term_font_family}}"
style = "Bold"

[font.bold_italic]
family = "{{term_font_family}}"
style = "Bold Italic"

[font.glyph_offset]
y = 1

[font.italic]
family = "{{term_font_family}}"
style = "Medium Italic"

[font.offset]
x = {{term_adjust_column_width}}
y = {{term_adjust_line_height}}

[hints]
alphabet = "asdfgqwertzxcvb"

[[hints.enabled]]
command = "xdg-open"
hyperlinks = true
post_processing = true
persist = false
mouse.enabled = true
binding = { key = "U", mods = "Control|Shift" }
regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`]+"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control|Alt"

[[keyboard.bindings]]
action = "ResetFontSize"
key = "Key0"
mods = "Control"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Control"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Control"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "K"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Copy"
key = "Y"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ClearSelection"
key = "Y"
mode = "Vi|~Search"
mods = "Shift"

[[keyboard.bindings]]
action = "ToggleViMode"
key = "Y"
mode = "Vi|~Search"
mods = "Shift"

[window]
decorations = "full"
dynamic_padding = true

[window.padding]
x = 4
y = 4

[window.dimensions]
columns = 125
lines = 38
