directory: "~/music/"
library: "~/music/library.db"
asciify_paths: no
art_filename: cover
max_filename_length: 150
threaded: yes
original_date: yes
ui:
    color: yes
paths:
   default: '%lower{%asciify{${albumartist}/${album}/${track}__${artist}__${title}}}'
replace:
    '[\s]': _
    '[+$#<>:"\?!\*\|\(\),\.\\''-]':
    '[&]': 'and'
    "[[]]":
plugins: fetchart embedart scrub edit zero
fetchart:
    auto: yes
    cautious: yes
    minwidth: 1000
    maxwidth: 1000
    enforce_ratio: yes
    cover_names: cover
    sources: filesystem
embedart:
    auto: yes
scrub:
    auto: yes
import:
    timid: yes
    default_action: apply
    detail: yes
    write: yes
    set_fields:
        genre: 'Rock'
    incremental: yes
format_item:
    '$albumartist | $artist | $artist_sort | $album | $year | $genre | $comments | $track | $title'
zero:
    auto: yes
    fields: comments
    update_database: yes
