[helpers]

[colors.variables]
# base colors
black = "#000000"
black_almost = "#12181a"
blue = "#116dd5"
gray_dark = "#c7c7c7"
gray_light = "#eeeeee"
green = "#008958"
green_dark = "#0b421a"
green_bright = "#2bb24c"
lavender = "#875faf"
magenta = "#ff3580"
red = "#ff4646"
white_almost = "#f9fafb"
white = "#ffffff"
yellow = "#f5a553"
yellow_light = "#e5dd80"
# the primary color of status bar ui elements
ui_primary = "#335e4e"
# the accent color for contrasting with the primary color, usual to denote
# selection of an item.
ui_accent = "#559e83"
# when you need a brighter/darker ui accent color to contrast with the primary
ui_accent_alt = "#1e382e"
# the text color when it appears inside ui elements
ui_text_accent = "#fcfdfe"
# when you need a brighter/darker text accent color
ui_text_accent_alt = "#c7c7c7"

# local variables:
#   fullname
#   email
[preferences.variables]
ui_font_family = "Ubuntu"
default_browser = "/usr/bin/firefox"
default_terminal_with_session = "alacritty --command ${HOME}/.dotfiles/scripts/tmux_start.sh"
default_terminal = "alacritty"

[terminal]
depends = ["vim"]

[terminal.files]
"bash/bashrc" = "~/.bashrc"
"bash/bashrc.func" = "~/.bashrc.func"
"git/gitconfig" = "~/.config/git/config"
"tmux/tmux.conf" = "~/.tmux.conf"
"ncmpcpp/config" = "~/.config/ncmpcpp/config"
"ncmpcpp/bindings" = "~/.config/ncmpcpp/bindings"
"ranger/rc.conf" = "~/.config/ranger/rc.conf"
"w3m/config" = "~/.w3m/config"
"w3m/keymap" = "~/.w3m/keymap"
"etc/inputrc" = "~/.inputrc"

[terminal.variables]
term_font_family = "CommitMono Nerd Font Propo"
term_font_family_bold = "Ubuntu Mono Bold"
term_font_family_italic = "Ubuntu Mono Italic"
term_font_family_bold_italic = "Ubuntu Mono Bold Italic"
term_font_size = 10
term_adjust_line_height = 4
term_adjust_column_width = 0
term_window_padding_width = 0.0
fzf_shell_completions = "/usr/share/fzf/completion.bash"
fzf_shell_bindings = "/usr/share/fzf/key-bindings.bash"
tmux_clipboard_cmd = "xclip -in -selection clipboard"

[vim.files]
"vim/vimrc" = "~/.vim/vimrc"
"vim/after" = "~/.vim/after"
"vim/ftplugin" = "~/.vim/ftplugin"
"vim/colors/olive.vim" = "~/.vim/colors/olive.vim"
"vim/autoload/functions.vim" = "~/.vim/autoload/functions.vim"
"vim/autoload/airline/themes/olive.vim" = "~/.vim/autoload/airline/themes/olive.vim"
"vim-plug/plug.vim" = "~/.vim/autoload/plug.vim"

[x11.files]
"xconfig/Xresources" = "~/.Xresources"

[x11.variables]
xresources_cursor_size = 24
xresources_dpi = 96

[i3.files]
"i3/config" = "~/.config/i3/config"

[i3.variables]
i3_window_font_size = 9
i3_border_width = 3
i3_locker = "/usr/bin/xsecurelock"

[polybar.files]
"polybar/config" = "~/.config/polybar/config"
"polybar/launch.sh" = "~/.config/polybar/launch.sh"
"polybar/notifications.sh" = "~/.config/polybar/notifications.sh"
"polybar/pavolume.sh" = "~/.config/polybar/pavolume.sh"

[polybar.variables]
polybar_modules_right = "mpd pulseaudio notifications date time tray"
polybar_font_zero = "CommitMono Nerd Font Propo:weight=bold:size=9;2"
polybar_font_one = "Noto Sans Mono CJK SC:size=10;1"
polybar_font_two = "Material Design Icons:size=10;3"
polybar_height = 18
polybar_power_battery = "BAT0"
polybar_power_adapter = "AC"

[rofi.files]
"rofi/config.rasi" = "~/.config/rofi/config.rasi"
"rofi/olive.rasi" = "~/.config/rofi/olive.rasi"
"rofi/dmenu.rasi" = "~/.config/rofi/dmenu.rasi"
"rofi-pass/config" = "~/.config/rofi-pass/config"

[rofi.variables]
rofi_font_family = "Cartograph CF"
rofi_font_size = 10

[greenclip.files]
#   greenclip_history_file
"greenclip/greenclip.toml" = "~/.config/greenclip.toml"

[dunst.files]
"dunst/dunstrc" = "~/.config/dunst/dunstrc"

[dunst.variables]
dunst_additional_settings = ""
dunst_font_size = 9
dunst_width = 400
dunst_offset = "10x10"

[gui_common.files]

[gui_common.variables]

[beets.files]
"beets/config.yaml" = "~/.config/beets/config.yaml"

[alacritty.files]
"alacritty/alacritty.toml" = "~/.config/alacritty/alacritty.toml"

[yay.files]
"yay/config.json" = "~/.config/yay/config.json"

[gvim.files]
"vim/gvimrc" = "~/.vim/gvimrc"

[tridactyl.files]
"tridactyl/tridactylrc" =  "~/.config/tridactyl/tridactylrc"
"tridactyl/olive.css" =  "~/.config/tridactyl/themes/olive.css"

[sway.files]
"sway/config" = "~/.config/sway/config"

[sway.variables]
sway_border_width = 3

[firefox.files]
"firefox/profile/chrome/userChrome.css" = ""

[kanshi.files]
"kanshi/config" = "~/.config/kanshi/config"

[waybar.files]
"waybar/config" = "~/.config/waybar/config"
"waybar/style.css" = "~/.config/waybar/style.css"

[swaylock.files]
"swaylock/config" = "~/.config/swaylock/config"

[flameshot.files]
"flameshot/flameshot.ini" = "~/.config/flameshot/flameshot.ini"

[flameshot.variables]
flameshot_save_path = ""

[ripgrep.files]
"ripgrep/rgignore" = "~/.config/ripgrep/rgignore"
"ripgrep/rgrc" = "~/.config/ripgrep/rgrc"
