# .bashrc

set -o vi

# Source global definitions
if [ -f /etc/bashrc ]; then
    . /etc/bashrc
fi

# enable programmable completion features
if [ -f /etc/bash_completion ] && ! shopt -oq posix; then
    . /etc/bash_completion
fi

[ -e ~/.dircolors ] && eval $(dircolors -b ~/.dircolors) || eval $(dircolors -b)

export PATH="$PATH:${HOME}/.local/bin"

# Uncomment the following line if you don't like systemctl's auto-paging feature:
export SYSTEMD_PAGER="less"

shopt -s histappend
shopt -s histverify

# for setting history length see HISTSIZE and HISTFILESIZE in bash(1)
export HISTSIZE=10000
export HISTFILESIZE=10000
export HISTCONTROL=ignorespace

# Immediately append to history
export PROMPT_COMMAND="history -a; history -c; history -r; $PROMPT_COMMAND"

color_prompt=yes

parse_git_branch() {
    git branch 2> /dev/null | awk '/^\*/ {printf " (%s)", $NF}'
}

show_bg_jobs() {
    count=$(jobs -s | wc -l)
    if [ $count -gt 0 ]; then
        printf " (%s)" "$count"
    fi
}

# Exports
export EDITOR=vim
if [ -z ${SSH_CLIENT+x} ]; then
    # If the ssh client variable isn't set, then this is a local terminal and
    # use the regular prompt color
    export PS1="\[\e[00;32m\][ \[\e[01;32m\]\u@\h:\[\e[00;34m\]\w\[\e[00;33m\]\$(parse_git_branch)\$(show_bg_jobs)\[\e[00;32m\] ]\n\[\e[00;32m\]$ \[\e[0m\]"
else
    # Else this is an ssh session. Change the prompt colors so it's more
    # obvious this isn't a local machine
    export PS1="\[\e[00;36m\][ \[\e[01;36m\]\u@\h:\[\e[00;33m\]\w\[\e[00;31m\]\$(parse_git_branch)\$(show_bg_jobs)\[\e[00;36m\] ]\n\[\e[00;36m\]$ \[\e[0m\]"
fi

# man pager color -- escapes for urxvt/xterm
# see termcap manpage for definitions
export GROFF_NO_SGR=1                       # output ANSI color escape sequences in raw form
export LESS_TERMCAP_mb=$'\E[01;31m'         # blinking
export LESS_TERMCAP_md=$'\E[01;32m'         # bold          headings            -> green
export LESS_TERMCAP_so=$'\E[01;37;43m'      # standout      statusbar/search    -> highlight grey background and black text
export LESS_TERMCAP_me=$'\E[0m'             # end all modes like so, us, mb, md and mr
export LESS_TERMCAP_se=$'\E[0m'             # end standout-mode
export LESS_TERMCAP_ue=$'\E[0m'             # end underline

# don't expand the tilde
_expand() {
    return 0;
}

# User specific aliases and functions
alias gits="git status"
alias c="clear -x"
alias ls="ls --color=auto --file-type -X"
alias ll="ls -alh --color=auto --group-directories-first"
alias grep='grep --color=auto'
alias vi="vim"
alias vp="vim -R -"
alias ring="echo -e '\a'"
alias pc="pass show -c"

# fzf configuration
if [[ -f "{{fzf_shell_completions}}" ]]; then
    source "{{fzf_shell_completions}}"
fi
if [[ -f "{{fzf_shell_bindings}}" ]]; then
    source "{{fzf_shell_bindings}}"
fi
export FZF_ALT_C_OPTS="--preview 'tree -C {} | head -200'"
export FZF_DEFAULT_OPTS='--height 60%'
export FZF_DEFAULT_COMMAND='rg --files --hidden --no-ignore-vcs --follow'
export FZF_CTRL_T_COMMAND=$FZF_DEFAULT_COMMAND

export RIPGREP_CONFIG_PATH="${HOME}/.config/ripgrep/rgrc"

# Load optional functions file
if [ -f ~/.bashrc.func ]; then
    source ~/.bashrc.func
fi

# Override with any local settings not tracked
if [ -f ~/.bashrc.local ]; then
    source ~/.bashrc.local
fi
